export const LANGUAGES = [
  { value: null, name: 'All Languages' },
  { value: '1c-enterprise', name: '1C Enterprise' },
  { value: 'abap', name: 'ABAP' },
  { value: 'abnf', name: 'ABNF' },
  { value: 'actionscript', name: 'ActionScript' },
  { value: 'ada', name: 'Ada' },
  { value: 'adobe-font-metrics', name: 'Adobe Font Metrics' },
  { value: 'agda', name: 'Agda' },
  { value: 'ags-script', name: 'AGS Script' },
  { value: 'alloy', name: 'Alloy' },
  { value: 'alpine-abuild', name: 'Alpine Abuild' },
  { value: 'ampl', name: 'AMPL' },
  { value: 'angelscript', name: 'AngelScript' },
  { value: 'ant-build-system', name: 'Ant Build System' },
  { value: 'antlr', name: 'ANTLR' },
  { value: 'apacheconf', name: 'ApacheConf' },
  { value: 'apex', name: 'Apex' },
  { value: 'api-blueprint', name: 'API Blueprint' },
  { value: 'apl', name: 'APL' },
  { value: 'apollo-guidance-computer', name: 'Apollo Guidance Computer' },
  { value: 'applescript', name: 'AppleScript' },
  { value: 'arc', name: 'Arc' },
  { value: 'asciidoc', name: 'AsciiDoc' },
  { value: 'asn.1', name: 'ASN.1' },
  { value: 'asp', name: 'ASP' },
  { value: 'aspectj', name: 'AspectJ' },
  { value: 'assembly', name: 'Assembly' },
  { value: 'ats', name: 'ATS' },
  { value: 'augeas', name: 'Augeas' },
  { value: 'autohotkey', name: 'AutoHotkey' },
  { value: 'autoit', name: 'AutoIt' },
  { value: 'awk', name: 'Awk' },
  { value: 'ballerina', name: 'Ballerina' },
  { value: 'batchfile', name: 'Batchfile' },
  { value: 'befunge', name: 'Befunge' },
  { value: 'bison', name: 'Bison' },
  { value: 'bitbake', name: 'BitBake' },
  { value: 'blade', name: 'Blade' },
  { value: 'blitzbasic', name: 'BlitzBasic' },
  { value: 'blitzmax', name: 'BlitzMax' },
  { value: 'bluespec', name: 'Bluespec' },
  { value: 'boo', name: 'Boo' },
  { value: 'brainfuck', name: 'Brainfuck' },
  { value: 'brightscript', name: 'Brightscript' },
  { value: 'bro', name: 'Bro' },
  { value: 'c', name: 'C' },
  { value: 'c%23', name: 'C#' },
  { value: 'c++', name: 'C++' },
  { value: 'c-objdump', name: 'C-ObjDump' },
  { value: 'c2hs-haskell', name: 'C2hs Haskell' },
  { value: "cap'n-proto", name: "Cap'n Proto" },
  { value: 'cartocss', name: 'CartoCSS' },
  { value: 'ceylon', name: 'Ceylon' },
  { value: 'chapel', name: 'Chapel' },
  { value: 'charity', name: 'Charity' },
  { value: 'chuck', name: 'ChucK' },
  { value: 'cirru', name: 'Cirru' },
  { value: 'clarion', name: 'Clarion' },
  { value: 'clean', name: 'Clean' },
  { value: 'click', name: 'Click' },
  { value: 'clips', name: 'CLIPS' },
  { value: 'clojure', name: 'Clojure' },
  { value: 'closure-templates', name: 'Closure Templates' },
  {
    value: 'cloud-firestore-security-rules',
    name: 'Cloud Firestore Security Rules',
  },
  { value: 'cmake', name: 'CMake' },
  { value: 'cobol', name: 'COBOL' },
  { value: 'coffeescript', name: 'CoffeeScript' },
  { value: 'coldfusion', name: 'ColdFusion' },
  { value: 'coldfusion-cfc', name: 'ColdFusion CFC' },
  { value: 'collada', name: 'COLLADA' },
  { value: 'common-lisp', name: 'Common Lisp' },
  { value: 'common-workflow-language', name: 'Common Workflow Language' },
  { value: 'component-pascal', name: 'Component Pascal' },
  { value: 'conll-u', name: 'CoNLL-U' },
  { value: 'cool', name: 'Cool' },
  { value: 'coq', name: 'Coq' },
  { value: 'cpp-objdump', name: 'Cpp-ObjDump' },
  { value: 'creole', name: 'Creole' },
  { value: 'crystal', name: 'Crystal' },
  { value: 'cson', name: 'CSON' },
  { value: 'csound', name: 'Csound' },
  { value: 'csound-document', name: 'Csound Document' },
  { value: 'csound-score', name: 'Csound Score' },
  { value: 'css', name: 'CSS' },
  { value: 'csv', name: 'CSV' },
  { value: 'cuda', name: 'Cuda' },
  { value: 'cweb', name: 'CWeb' },
  { value: 'cycript', name: 'Cycript' },
  { value: 'cython', name: 'Cython' },
  { value: 'd', name: 'D' },
  { value: 'd-objdump', name: 'D-ObjDump' },
  { value: 'darcs-patch', name: 'Darcs Patch' },
  { value: 'dart', name: 'Dart' },
  { value: 'dataweave', name: 'DataWeave' },
  { value: 'desktop', name: 'desktop' },
  { value: 'diff', name: 'Diff' },
  { value: 'digital-command-language', name: 'DIGITAL Command Language' },
  { value: 'dm', name: 'DM' },
  { value: 'dns-zone', name: 'DNS Zone' },
  { value: 'dockerfile', name: 'Dockerfile' },
  { value: 'dogescript', name: 'Dogescript' },
  { value: 'dtrace', name: 'DTrace' },
  { value: 'dylan', name: 'Dylan' },
  { value: 'e', name: 'E' },
  { value: 'eagle', name: 'Eagle' },
  { value: 'easybuild', name: 'Easybuild' },
  { value: 'ebnf', name: 'EBNF' },
  { value: 'ec', name: 'eC' },
  { value: 'ecere-projects', name: 'Ecere Projects' },
  { value: 'ecl', name: 'ECL' },
  { value: 'eclipse', name: 'ECLiPSe' },
  { value: 'edje-data-collection', name: 'Edje Data Collection' },
  { value: 'edn', name: 'edn' },
  { value: 'eiffel', name: 'Eiffel' },
  { value: 'ejs', name: 'EJS' },
  { value: 'elixir', name: 'Elixir' },
  { value: 'elm', name: 'Elm' },
  { value: 'emacs-lisp', name: 'Emacs Lisp' },
  { value: 'emberscript', name: 'EmberScript' },
  { value: 'eq', name: 'EQ' },
  { value: 'erlang', name: 'Erlang' },
  { value: 'f%23', name: 'F#' },
  { value: 'factor', name: 'Factor' },
  { value: 'fancy', name: 'Fancy' },
  { value: 'fantom', name: 'Fantom' },
  { value: 'filebench-wml', name: 'Filebench WML' },
  { value: 'filterscript', name: 'Filterscript' },
  { value: 'fish', name: 'fish' },
  { value: 'flux', name: 'FLUX' },
  { value: 'formatted', name: 'Formatted' },
  { value: 'forth', name: 'Forth' },
  { value: 'fortran', name: 'Fortran' },
  { value: 'freemarker', name: 'FreeMarker' },
  { value: 'frege', name: 'Frege' },
  { value: 'g-code', name: 'G-code' },
  { value: 'game-maker-language', name: 'Game Maker Language' },
  { value: 'gams', name: 'GAMS' },
  { value: 'gap', name: 'GAP' },
  { value: 'gcc-machine-description', name: 'GCC Machine Description' },
  { value: 'gdb', name: 'GDB' },
  { value: 'gdscript', name: 'GDScript' },
  { value: 'genie', name: 'Genie' },
  { value: 'genshi', name: 'Genshi' },
  { value: 'gentoo-ebuild', name: 'Gentoo Ebuild' },
  { value: 'gentoo-eclass', name: 'Gentoo Eclass' },
  { value: 'gerber-image', name: 'Gerber Image' },
  { value: 'gettext-catalog', name: 'Gettext Catalog' },
  { value: 'gherkin', name: 'Gherkin' },
  { value: 'glsl', name: 'GLSL' },
  { value: 'glyph', name: 'Glyph' },
  { value: 'gn', name: 'GN' },
  { value: 'gnuplot', name: 'Gnuplot' },
  { value: 'go', name: 'Go' },
  { value: 'golo', name: 'Golo' },
  { value: 'gosu', name: 'Gosu' },
  { value: 'grace', name: 'Grace' },
  { value: 'gradle', name: 'Gradle' },
  { value: 'grammatical-framework', name: 'Grammatical Framework' },
  { value: 'graph-modeling-language', name: 'Graph Modeling Language' },
  { value: 'graphql', name: 'GraphQL' },
  { value: 'graphviz-(dot)', name: 'Graphviz (DOT)' },
  { value: 'groovy', name: 'Groovy' },
  { value: 'groovy-server-pages', name: 'Groovy Server Pages' },
  { value: 'hack', name: 'Hack' },
  { value: 'haml', name: 'Haml' },
  { value: 'handlebars', name: 'Handlebars' },
  { value: 'harbour', name: 'Harbour' },
  { value: 'haskell', name: 'Haskell' },
  { value: 'haxe', name: 'Haxe' },
  { value: 'hcl', name: 'HCL' },
  { value: 'hiveql', name: 'HiveQL' },
  { value: 'hlsl', name: 'HLSL' },
  { value: 'html', name: 'HTML' },
  { value: 'html+django', name: 'HTML+Django' },
  { value: 'html+ecr', name: 'HTML+ECR' },
  { value: 'html+eex', name: 'HTML+EEX' },
  { value: 'html+erb', name: 'HTML+ERB' },
  { value: 'html+php', name: 'HTML+PHP' },
  { value: 'http', name: 'HTTP' },
  { value: 'hxml', name: 'HXML' },
  { value: 'hy', name: 'Hy' },
  { value: 'hyphy', name: 'HyPhy' },
  { value: 'idl', name: 'IDL' },
  { value: 'idris', name: 'Idris' },
  { value: 'igor-pro', name: 'IGOR Pro' },
  { value: 'inform-7', name: 'Inform 7' },
  { value: 'ini', name: 'INI' },
  { value: 'inno-setup', name: 'Inno Setup' },
  { value: 'io', name: 'Io' },
  { value: 'ioke', name: 'Ioke' },
  { value: 'irc-log', name: 'IRC log' },
  { value: 'isabelle', name: 'Isabelle' },
  { value: 'isabelle-root', name: 'Isabelle ROOT' },
  { value: 'j', name: 'J' },
  { value: 'jasmin', name: 'Jasmin' },
  { value: 'java', name: 'Java' },
  { value: 'java-server-pages', name: 'Java Server Pages' },
  { value: 'javascript', name: 'JavaScript' },
  { value: 'jflex', name: 'JFlex' },
  { value: 'jison', name: 'Jison' },
  { value: 'jison-lex', name: 'Jison Lex' },
  { value: 'jolie', name: 'Jolie' },
  { value: 'json', name: 'JSON' },
  { value: 'json-with-comments', name: 'JSON with Comments' },
  { value: 'json5', name: 'JSON5' },
  { value: 'jsoniq', name: 'JSONiq' },
  { value: 'jsonld', name: 'JSONLD' },
  { value: 'jsx', name: 'JSX' },
  { value: 'julia', name: 'Julia' },
  { value: 'jupyter-notebook', name: 'Jupyter Notebook' },
  { value: 'kicad-layout', name: 'KiCad Layout' },
  { value: 'kicad-legacy-layout', name: 'KiCad Legacy Layout' },
  { value: 'kicad-schematic', name: 'KiCad Schematic' },
  { value: 'kit', name: 'Kit' },
  { value: 'kotlin', name: 'Kotlin' },
  { value: 'krl', name: 'KRL' },
  { value: 'labview', name: 'LabVIEW' },
  { value: 'lasso', name: 'Lasso' },
  { value: 'latte', name: 'Latte' },
  { value: 'lean', name: 'Lean' },
  { value: 'less', name: 'Less' },
  { value: 'lex', name: 'Lex' },
  { value: 'lfe', name: 'LFE' },
  { value: 'lilypond', name: 'LilyPond' },
  { value: 'limbo', name: 'Limbo' },
  { value: 'linker-script', name: 'Linker Script' },
  { value: 'linux-kernel-module', name: 'Linux Kernel Module' },
  { value: 'liquid', name: 'Liquid' },
  { value: 'literate-agda', name: 'Literate Agda' },
  { value: 'literate-coffeescript', name: 'Literate CoffeeScript' },
  { value: 'literate-haskell', name: 'Literate Haskell' },
  { value: 'livescript', name: 'LiveScript' },
  { value: 'llvm', name: 'LLVM' },
  { value: 'logos', name: 'Logos' },
  { value: 'logtalk', name: 'Logtalk' },
  { value: 'lolcode', name: 'LOLCODE' },
  { value: 'lookml', name: 'LookML' },
  { value: 'loomscript', name: 'LoomScript' },
  { value: 'lsl', name: 'LSL' },
  { value: 'lua', name: 'Lua' },
  { value: 'm', name: 'M' },
  { value: 'm4', name: 'M4' },
  { value: 'm4sugar', name: 'M4Sugar' },
  { value: 'makefile', name: 'Makefile' },
  { value: 'mako', name: 'Mako' },
  { value: 'markdown', name: 'Markdown' },
  { value: 'marko', name: 'Marko' },
  { value: 'mask', name: 'Mask' },
  { value: 'mathematica', name: 'Mathematica' },
  { value: 'matlab', name: 'Matlab' },
  { value: 'maven-pom', name: 'Maven POM' },
  { value: 'max', name: 'Max' },
  { value: 'maxscript', name: 'MAXScript' },
  { value: 'mediawiki', name: 'MediaWiki' },
  { value: 'mercury', name: 'Mercury' },
  { value: 'meson', name: 'Meson' },
  { value: 'metal', name: 'Metal' },
  { value: 'minid', name: 'MiniD' },
  { value: 'mirah', name: 'Mirah' },
  { value: 'modelica', name: 'Modelica' },
  { value: 'modula-2', name: 'Modula-2' },
  { value: 'modula-3', name: 'Modula-3' },
  { value: 'module-management-system', name: 'Module Management System' },
  { value: 'monkey', name: 'Monkey' },
  { value: 'moocode', name: 'Moocode' },
  { value: 'moonscript', name: 'MoonScript' },
  { value: 'mql4', name: 'MQL4' },
  { value: 'mql5', name: 'MQL5' },
  { value: 'mtml', name: 'MTML' },
  { value: 'muf', name: 'MUF' },
  { value: 'mupad', name: 'mupad' },
  { value: 'myghty', name: 'Myghty' },
  { value: 'ncl', name: 'NCL' },
  { value: 'nearley', name: 'Nearley' },
  { value: 'nemerle', name: 'Nemerle' },
  { value: 'nesc', name: 'nesC' },
  { value: 'netlinx', name: 'NetLinx' },
  { value: 'netlinx+erb', name: 'NetLinx+ERB' },
  { value: 'netlogo', name: 'NetLogo' },
  { value: 'newlisp', name: 'NewLisp' },
  { value: 'nextflow', name: 'Nextflow' },
  { value: 'nginx', name: 'Nginx' },
  { value: 'nim', name: 'Nim' },
  { value: 'ninja', name: 'Ninja' },
  { value: 'nit', name: 'Nit' },
  { value: 'nix', name: 'Nix' },
  { value: 'nl', name: 'NL' },
  { value: 'nsis', name: 'NSIS' },
  { value: 'nu', name: 'Nu' },
  { value: 'numpy', name: 'NumPy' },
  { value: 'objdump', name: 'ObjDump' },
  { value: 'objective-c', name: 'Objective-C' },
  { value: 'objective-c++', name: 'Objective-C++' },
  { value: 'objective-j', name: 'Objective-J' },
  { value: 'ocaml', name: 'OCaml' },
  { value: 'omgrofl', name: 'Omgrofl' },
  { value: 'ooc', name: 'ooc' },
  { value: 'opa', name: 'Opa' },
  { value: 'opal', name: 'Opal' },
  { value: 'opencl', name: 'OpenCL' },
  { value: 'openedge-abl', name: 'OpenEdge ABL' },
  { value: 'openrc-runscript', name: 'OpenRC runscript' },
  { value: 'openscad', name: 'OpenSCAD' },
  { value: 'opentype-feature-file', name: 'OpenType Feature File' },
  { value: 'org', name: 'Org' },
  { value: 'ox', name: 'Ox' },
  { value: 'oxygene', name: 'Oxygene' },
  { value: 'oz', name: 'Oz' },
  { value: 'p4', name: 'P4' },
  { value: 'pan', name: 'Pan' },
  { value: 'papyrus', name: 'Papyrus' },
  { value: 'parrot', name: 'Parrot' },
  { value: 'parrot-assembly', name: 'Parrot Assembly' },
  {
    value: 'parrot-internal-representation',
    name: 'Parrot Internal Representation',
  },
  { value: 'pascal', name: 'Pascal' },
  { value: 'pawn', name: 'PAWN' },
  { value: 'pep8', name: 'Pep8' },
  { value: 'perl', name: 'Perl' },
  { value: 'perl-6', name: 'Perl 6' },
  { value: 'php', name: 'PHP' },
  { value: 'pic', name: 'Pic' },
  { value: 'pickle', name: 'Pickle' },
  { value: 'picolisp', name: 'PicoLisp' },
  { value: 'piglatin', name: 'PigLatin' },
  { value: 'pike', name: 'Pike' },
  { value: 'plpgsql', name: 'PLpgSQL' },
  { value: 'plsql', name: 'PLSQL' },
  { value: 'pod', name: 'Pod' },
  { value: 'pogoscript', name: 'PogoScript' },
  { value: 'pony', name: 'Pony' },
  { value: 'postcss', name: 'PostCSS' },
  { value: 'postscript', name: 'PostScript' },
  { value: 'pov-ray-sdl', name: 'POV-Ray SDL' },
  { value: 'powerbuilder', name: 'PowerBuilder' },
  { value: 'powershell', name: 'PowerShell' },
  { value: 'processing', name: 'Processing' },
  { value: 'prolog', name: 'Prolog' },
  { value: 'propeller-spin', name: 'Propeller Spin' },
  { value: 'protocol-buffer', name: 'Protocol Buffer' },
  { value: 'public-key', name: 'Public Key' },
  { value: 'pug', name: 'Pug' },
  { value: 'puppet', name: 'Puppet' },
  { value: 'pure-data', name: 'Pure Data' },
  { value: 'purebasic', name: 'PureBasic' },
  { value: 'purescript', name: 'PureScript' },
  { value: 'python', name: 'Python' },
  { value: 'python-console', name: 'Python console' },
  { value: 'python-traceback', name: 'Python traceback' },
  { value: 'q', name: 'q' },
  { value: 'qmake', name: 'QMake' },
  { value: 'qml', name: 'QML' },
  { value: 'r', name: 'R' },
  { value: 'racket', name: 'Racket' },
  { value: 'ragel', name: 'Ragel' },
  { value: 'raml', name: 'RAML' },
  { value: 'rascal', name: 'Rascal' },
  { value: 'raw-token-data', name: 'Raw token data' },
  { value: 'rdoc', name: 'RDoc' },
  { value: 'realbasic', name: 'REALbasic' },
  { value: 'reason', name: 'Reason' },
  { value: 'rebol', name: 'Rebol' },
  { value: 'red', name: 'Red' },
  { value: 'redcode', name: 'Redcode' },
  { value: 'regular-expression', name: 'Regular Expression' },
  { value: "ren'py", name: "Ren'Py" },
  { value: 'renderscript', name: 'RenderScript' },
  { value: 'restructuredtext', name: 'reStructuredText' },
  { value: 'rexx', name: 'REXX' },
  { value: 'rhtml', name: 'RHTML' },
  { value: 'ring', name: 'Ring' },
  { value: 'rmarkdown', name: 'RMarkdown' },
  { value: 'robotframework', name: 'RobotFramework' },
  { value: 'roff', name: 'Roff' },
  { value: 'rouge', name: 'Rouge' },
  { value: 'rpc', name: 'RPC' },
  { value: 'rpm-spec', name: 'RPM Spec' },
  { value: 'ruby', name: 'Ruby' },
  { value: 'runoff', name: 'RUNOFF' },
  { value: 'rust', name: 'Rust' },
  { value: 'sage', name: 'Sage' },
  { value: 'saltstack', name: 'SaltStack' },
  { value: 'sas', name: 'SAS' },
  { value: 'sass', name: 'Sass' },
  { value: 'scala', name: 'Scala' },
  { value: 'scaml', name: 'Scaml' },
  { value: 'scheme', name: 'Scheme' },
  { value: 'scilab', name: 'Scilab' },
  { value: 'scss', name: 'SCSS' },
  { value: 'sed', name: 'sed' },
  { value: 'self', name: 'Self' },
  { value: 'shaderlab', name: 'ShaderLab' },
  { value: 'shell', name: 'Shell' },
  { value: 'shellsession', name: 'ShellSession' },
  { value: 'shen', name: 'Shen' },
  { value: 'slash', name: 'Slash' },
  { value: 'slim', name: 'Slim' },
  { value: 'smali', name: 'Smali' },
  { value: 'smalltalk', name: 'Smalltalk' },
  { value: 'smarty', name: 'Smarty' },
  { value: 'smt', name: 'SMT' },
  { value: 'solidity', name: 'Solidity' },
  { value: 'sourcepawn', name: 'SourcePawn' },
  { value: 'sparql', name: 'SPARQL' },
  { value: 'spline-font-database', name: 'Spline Font Database' },
  { value: 'sqf', name: 'SQF' },
  { value: 'sql', name: 'SQL' },
  { value: 'sqlpl', name: 'SQLPL' },
  { value: 'squirrel', name: 'Squirrel' },
  { value: 'srecode-template', name: 'SRecode Template' },
  { value: 'stan', name: 'Stan' },
  { value: 'standard-ml', name: 'Standard ML' },
  { value: 'stata', name: 'Stata' },
  { value: 'ston', name: 'STON' },
  { value: 'stylus', name: 'Stylus' },
  { value: 'subrip-text', name: 'SubRip Text' },
  { value: 'sugarss', name: 'SugarSS' },
  { value: 'supercollider', name: 'SuperCollider' },
  { value: 'svg', name: 'SVG' },
  { value: 'swift', name: 'Swift' },
  { value: 'systemverilog', name: 'SystemVerilog' },
  { value: 'tcl', name: 'Tcl' },
  { value: 'tcsh', name: 'Tcsh' },
  { value: 'tea', name: 'Tea' },
  { value: 'terra', name: 'Terra' },
  { value: 'tex', name: 'TeX' },
  { value: 'text', name: 'Text' },
  { value: 'textile', name: 'Textile' },
  { value: 'thrift', name: 'Thrift' },
  { value: 'ti-program', name: 'TI Program' },
  { value: 'tla', name: 'TLA' },
  { value: 'toml', name: 'TOML' },
  { value: 'turing', name: 'Turing' },
  { value: 'turtle', name: 'Turtle' },
  { value: 'twig', name: 'Twig' },
  { value: 'txl', name: 'TXL' },
  { value: 'type-language', name: 'Type Language' },
  { value: 'typescript', name: 'TypeScript' },
  { value: 'unified-parallel-c', name: 'Unified Parallel C' },
  { value: 'unity3d-asset', name: 'Unity3D Asset' },
  { value: 'unix-assembly', name: 'Unix Assembly' },
  { value: 'uno', name: 'Uno' },
  { value: 'unrealscript', name: 'UnrealScript' },
  { value: 'urweb', name: 'UrWeb' },
  { value: 'vala', name: 'Vala' },
  { value: 'vcl', name: 'VCL' },
  { value: 'verilog', name: 'Verilog' },
  { value: 'vhdl', name: 'VHDL' },
  { value: 'vim-script', name: 'Vim script' },
  { value: 'visual-basic', name: 'Visual Basic' },
  { value: 'volt', name: 'Volt' },
  { value: 'vue', name: 'Vue' },
  { value: 'wavefront-material', name: 'Wavefront Material' },
  { value: 'wavefront-object', name: 'Wavefront Object' },
  { value: 'wdl', name: 'wdl' },
  { value: 'web-ontology-language', name: 'Web Ontology Language' },
  { value: 'webassembly', name: 'WebAssembly' },
  { value: 'webidl', name: 'WebIDL' },
  { value: 'wisp', name: 'wisp' },
  {
    value: 'world-of-warcraft-addon-data',
    name: 'World of Warcraft Addon Data',
  },
  { value: 'x-bitmap', name: 'X BitMap' },
  { value: 'x-pixmap', name: 'X PixMap' },
  { value: 'x10', name: 'X10' },
  { value: 'xbase', name: 'xBase' },
  { value: 'xc', name: 'XC' },
  { value: 'xcompose', name: 'XCompose' },
  { value: 'xml', name: 'XML' },
  { value: 'xojo', name: 'Xojo' },
  { value: 'xpages', name: 'XPages' },
  { value: 'xproc', name: 'XProc' },
  { value: 'xquery', name: 'XQuery' },
  { value: 'xs', name: 'XS' },
  { value: 'xslt', name: 'XSLT' },
  { value: 'xtend', name: 'Xtend' },
  { value: 'yacc', name: 'Yacc' },
  { value: 'yaml', name: 'YAML' },
  { value: 'yang', name: 'YANG' },
  { value: 'yara', name: 'YARA' },
  { value: 'zephir', name: 'Zephir' },
  { value: 'zimpl', name: 'Zimpl' },
];
